### ISSUE TITLE
PdfJs Viewer support for customizing the toolbar

### ISSUE THREAD

**Issue by wabson** [share-extras/media-viewers#12]
It should be possible to re-order and remove buttons and other toolbar controls, including separators.

It should be possible to specify 'modes' for each item, which control which pages the item appears on, e.g. document-details, dashboard, wiki-page, blog-post, etc.

**Comment by loftux** [comment]
As part of commit to fix #27 in function onComponentsLoaded  
this property is set:

this.disabledPageLinking = (Alfresco.constants.PAGEID==='document-details') ? false : true;  

My thought is that we re-work this so that if toolbar config has link button disabled this.disabledPageLinking is set to true. This way linking can be enabled for other pages where it will work, i.e. if someone creates a page that has just one instance of PdfJs viewer and no datatable paging that interfere.
