### ISSUE TITLE
Request extended the scale range in PdfJs viewer

### ISSUE THREAD

**Issue by amatsuur** [share-extras/media-viewers#19]
Hi, 

With modifying pdfjs.get.html.ftl, I could add a scale magnification of PdfJs? viewer up to 600%. That is, just adding <option value="6">600%</option> in <select id="${el}-scaleSelect"><select>. However I cannot enable 800% or 1000% even adding <option value="8">800%</option> or <option value="10">1000%</option>. This scale settings might be ludicrous, I know well, but my customer wants to see very fine-grained pdf files so I need to enable these scale setting. 
Please extend the range of scale of the viewer in the next release.

Also, when viewing a document with a big magnification such 400% or 600%, the operation of the document got to be very slow. Please enhance the processing time of the viewer if possible.   

Atsushi Matsuura

**Comment by loftux** [comment]
Since you have noted that these edge cases of magnification comes with a performance penalty I would not recommend to add this in as standard. Instead I recommend that you create a fork and add the requirements that are specific to your customer.

As for the processing time, we do use and external library (pdf.js) and this is what does all the rendering. Media viewers project will not likely start changing any of that core library. We do however try to track their progress and update to the latest libraries of pdf.js. There is a special branch (pdfjs) here that you can check out if you want to see if they have done some performance optimizations.
So eventually any performance enhancements made by the external pdf.js library will make it into this project.

**Comment by loftux** [comment]
Close as there are no further comments on this issue. Recommended to fork and use custom version for this edge case.
