### ISSUE TITLE
Webodf - add missing resources or remove completely

### ISSUE THREAD

**Issue by loftux** [share-extras/media-viewers#26]
The experimental Webodf viewer is missing the resources
extras/modules/webodf/webodf.css
extras/modules/webodf/webodf.js

Should we add those resources, or remove the Webodf completely?
Currently if you enable the webodf viewer it fails since the recourses are missing.

**Comment by wabson** [comment]
We cannot distribute WebODF from the share-extras project due to their AGPL license. The missing files are available from my personal GitHub space.

This is explained in the README ([link](https://github.com/share-extras/media-viewers#webodf))

_WebODF cannot be distributed with the add-in itself, so in order to use it you must also download the latest JAR file from the supporting [share-webodf](https://github.com/wabson/webodf-share/downloads) project and install it in the same way as the main media-viewers JAR file._

**Comment by loftux** [comment]
I missed that. Closing this issue.
